import type { FormValues } from "../utils/mapToApiPayload";

export const initialValues: FormValues = {
  clientId: "",
  caseStatusReceived: "",
  caseStatus: "pending",
  caseTitle: "",
  clientName: "",
  caseType: "",
  clientType: "individual",
  policeStation: "",
  numberInPoliceStation: "",
  dateInPoliceStation: "",
  investigatorName: "",
  investigativeAuthority: "",
  dateInOffice: "",
  firstName: "",
  secondName: "",
  countryCode: "+20",
  phone: "",
  civilId: "",
  legalStatus: "",
  nationality: "",
  country: "",
  address: "",
  email: "",
  prosecution: "",
  numberInProsecution: "",
  dateInProsecution: "",
  caseReceiptDate: "",
  contractStartDate: "",
  contractValue: "",
  contractDuration: "",
  contractImage: null,
  powerOfAttorneyImage: null,
  fixedFees: 0,
  profitPercentage: 0,
  notes: "",
  feeType: "",
  hasDiscount: false,
};
