import { SA, AE, QA, KW, BH, OM, EG, JO, LB, IQ, SY, PS, YE, SD, LY, TN, DZ, MA, MR, SO, DJ, KM, US, GB, CA, AU, IN, PK, CN, JP, DE, FR, IT, ES, TR, RU } from 'country-flag-icons/react/3x2';

export const COUNTRY_OPTIONS = [
    { value: "+966", iso: "SA", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+966</span> <SA className="w-5" /></div> },
    { value: "+971", iso: "AE", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+971</span> <AE className="w-5" /></div> },
    { value: "+974", iso: "QA", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+974</span> <QA className="w-5" /></div> },
    { value: "+965", iso: "KW", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+965</span> <KW className="w-5" /></div> },
    { value: "+973", iso: "BH", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+973</span> <BH className="w-5" /></div> },
    { value: "+968", iso: "OM", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+968</span> <OM className="w-5" /></div> },
    { value: "+20", iso: "EG", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+20</span> <EG className="w-5" /></div> },
    { value: "+962", iso: "JO", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+962</span> <JO className="w-5" /></div> },
    { value: "+961", iso: "LB", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+961</span> <LB className="w-5" /></div> },
    { value: "+964", iso: "IQ", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+964</span> <IQ className="w-5" /></div> },
    { value: "+963", iso: "SY", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+963</span> <SY className="w-5" /></div> },
    { value: "+970", iso: "PS", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+970</span> <PS className="w-5" /></div> },
    { value: "+967", iso: "YE", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+967</span> <YE className="w-5" /></div> },
    { value: "+249", iso: "SD", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+249</span> <SD className="w-5" /></div> },
    { value: "+218", iso: "LY", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+218</span> <LY className="w-5" /></div> },
    { value: "+216", iso: "TN", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+216</span> <TN className="w-5" /></div> },
    { value: "+213", iso: "DZ", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+213</span> <DZ className="w-5" /></div> },
    { value: "+212", iso: "MA", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+212</span> <MA className="w-5" /></div> },
    { value: "+222", iso: "MR", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+222</span> <MR className="w-5" /></div> },
    { value: "+252", iso: "SO", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+252</span> <SO className="w-5" /></div> },
    { value: "+253", iso: "DJ", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+253</span> <DJ className="w-5" /></div> },
    { value: "+269", iso: "KM", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+269</span> <KM className="w-5" /></div> },
    { value: "+1", iso: "US", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+1</span> <US className="w-5" /></div> },
    { value: "+44", iso: "GB", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+44</span> <GB className="w-5" /></div> },
    { value: "+1", iso: "CA", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+1</span> <CA className="w-5" /></div> },
    { value: "+61", iso: "AU", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+61</span> <AU className="w-5" /></div> },
    { value: "+91", iso: "IN", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+91</span> <IN className="w-5" /></div> },
    { value: "+92", iso: "PK", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+92</span> <PK className="w-5" /></div> },
    { value: "+86", iso: "CN", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+86</span> <CN className="w-5" /></div> },
    { value: "+81", iso: "JP", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+81</span> <JP className="w-5" /></div> },
    { value: "+49", iso: "DE", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+49</span> <DE className="w-5" /></div> },
    { value: "+33", iso: "FR", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+33</span> <FR className="w-5" /></div> },
    { value: "+39", iso: "IT", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+39</span> <IT className="w-5" /></div> },
    { value: "+34", iso: "ES", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+34</span> <ES className="w-5" /></div> },
    { value: "+90", iso: "TR", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+90</span> <TR className="w-5" /></div> },
    { value: "+7", iso: "RU", label: <div className="flex w-full items-center justify-between gap-2 px-1"><span dir="ltr">+7</span> <RU className="w-5" /></div> },
];
