name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      #- name: Run tests
       # run: |
        #  npm install
         # npm run build

      - name: Deploy to VPS
        if: success()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd /lawyer/lawyer-front
            git pull origin main
            npm install
            pm2 restart react-app || pm2 start "serve -s build -l 5174" --name react-app
            pm2 save            